### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by vendelieu** [lyqht/deepl-translate-github-action#11]
please add option to process multiple files, by passing path to files dir

**Comment by lyqht** [comment]
hi @vendelieu, you can set the github action to run on multiple files

```
name: Translate multiple files
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Translate README
        uses: lyqht/deepl-translate-github-action@v2.1.0
        with:
          target_languages: fr,ja
          input_file_path: docs/README.md
          output_file_name_pattern: docs/{language}/README.md
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}

      - name: Translate About page  
        uses: lyqht/deepl-translate-github-action@v2.1.0
        with:
          target_languages: fr,ja
          input_file_path: docs/about.md
          output_file_name_pattern: docs/{language}/about.md
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
```

this is so that you can set the output dir accordingly
